   <section class="generic animated fadeInUp delay1">
      <div class="container">

         <!-- title -->
         <div class="row text-center title">
           <?php if (isset($titulo) && $titulo != "") {echo '<h1>'.$titulo.'</h1>';}  ?>
                      <?php if (isset($subtitulo) && $subtitulo != "") {echo '<h2>'.$subtitulo.'</h2>';}  ?>

         </div>
         <!-- end title -->

						<p><strong>Fecha de entrada en vigencia de este Aviso de Privacidad:</strong> 8 de Marzo de 2016</p>
<p style="text-align: justify;"><strong>Fecha de última Actualización:</strong> 1 de Octubre del 2016.</p>
<p style="text-align: justify;">Nosotros respetamos su privacidad y estamos comprometidos a mantener y utilizar esta información de manera responsable. Esta política de privacidad se refiere al uso y divulgación de información personal que obtenemos de usted.</p>
<p style="text-align: justify;"><strong>¿Qué son “Datos Personales” según este Aviso de Privacidad?</strong></p>
<p style="text-align: justify;">&#8220;Datos Personales&#8221; significa cualquier información concerniente a una persona física identificada o identificable y que es recabada por cualquier medio por Todo en Tutores SA de CV.</p>
<p style="text-align: justify;"><strong>¿Quién es el Responsable de la protección de sus datos personales?</strong></p>
<p style="text-align: justify;">Todo en Tutores SA de CV con domicilio en Cafetales no 90 Int 3, Colonia Granjas Coapa, Delegación Tlalpan, México, Distrito Federal, es el responsable del tratamiento de sus datos personales de conformidad con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares publicada en el Diario Oficial de la Federación el 5 de julio de 2010.</p>
<p style="text-align: justify;"><strong>¿Cómo contactarnos?</strong></p>
<p style="text-align: justify;">Vía correo electrónico a la dirección <a href="mailto:contacto-tlalpan@tutordoctor.com.mx">contacto-tlalpan@tutordoctor.com.mx</a></p>
<h2 style="text-align: justify;">Información que recopilamos sobre usted</h2>
<p style="text-align: justify;">Cualquier información personal que usted nos proporciona es mantenida en servidores seguros y nuestros sistemas internos. Nosotros recopilamos información personal cuando usted realiza alguna consulta en línea a través de nuestro formulario de contacto en nuestro sitio web Todo en Tutores SA de CV. También podemos recopilar información personal de usted en nuestras tiendas o a través de nuestro material y papelería impresa para uso publicitario y de venta. Esta información puede incluir, pero no limitado a, su información de contacto (por ejemplo, las direcciones de su nombre, dirección de correo electrónico, envío y número de teléfono). Su información personal es voluntaria, sin embargo, si usted no proporciona parte o la totalidad de la información que solicitamos, no podemos ser capaces de ofrecerle algunos productos o servicios. Al acceder a este sitio web, recopilamos la dirección IP del ordenador que está utilizando para navegar por el sitio. Si la dirección es una dirección IP &#8220;estática&#8221; o fijo, en ciertas circunstancias podría teóricamente ser capaz de identificarlo. Sin embargo, sólo recogemos este tipo de información para compilar las estadísticas de uso de forma anónima, nosotros no recopilamos datos de dirección IP para identificarlo. No vamos a mantener cualquier otro tipo de información personal, como resultado de su acceso y uso del sitio.</p>
<h2>Cómo usamos y compartimos esta información</h2>
<p>Cuando usted proporciona su dirección postal, ya sea al solicitar un catálogo o realizar un pedido a través de este sitio web, usted puede recibir por correo electrónico los catálogos de nosotros. Cuando usted realiza un pedido en cualquiera de nuestros sitios web, podemos usar esta información para procesar y dar seguimiento de su pedido, y en contacto con usted por correo electrónico o teléfono si tiene alguna pregunta o inquietud con respecto a su pedido. También mantenemos un registro de sus compras realizadas, y combinar esto con la información que a proporcionado en nuestras oficina, por via electrónica o por teléfono con el fin de brindarle un mejor servicio. Es posible que combinemos información que nos proporcione con información demográfica, información que está disponible al público, así como información acerca de sus preferencias de productos e intereses con el fin de mejorar el diseño de nuestro sitio y mejorar la presentación de nuestros servicios y productos. No revelaremos su información personal a terceros para sus propios fines de marketing sin su consentimiento de aceptación. Nosotros no recopilamos ni procesamos ningún &#8221; dato sensible&#8221; sobre usted (como los datos sobre la salud o asuntos igualmente sensibles). Podemos compartir algunos o todos los datos personales recogidos a través de este sitio web con nuestros afiliados, que utilizan estos datos de acuerdo con esta Política de Privacidad. En el caso de venta de una parte o todo nuestro negocio, nosotros podemos revelar su información personal a un comprador que se compromete a cumplir con los términos y condiciones de esta política de privacidad y se compromete a proteger su privacidad. También debe tener en cuenta que podemos revelar información específica sobre usted si se requiere o permite hacerlo por ley, pedidos del gobierno, proceso u orden judicial o basada en nuestra creencia de buena fe que es necesario para cumplir con dicha ley, la solicitud de una orden judicial o para proteger a los usuarios de nuestros sitios web o el público.</p>
<h2>Acceso y corrección de datos personales</h2>
<p>Usted también puede hacer una solicitud a nuestra empresa para modificar la información que presentó como parte del proceso de registro de compra. Usted también tiene el derecho de pedirnos la información que tenemos acerca de usted y de pedirnos que eliminemos o modifiquemos cualquier información incorrecta. También puede oponerse al tratamiento de sus datos personales y revocar el consentimiento prestado a nosotros (o realizar cualquier consulta sobre esta política de privacidad o presentar una queja) poniéndose en contacto con nosotros. Vía correo electrónico a la dirección contacto-tlalpan@tutordoctor.com.mx</p>
<h2>¿Para qué fines recabamos y utilizamos sus datos personales?</h2>
<p>Sus datos personales serán utilizados para una o varias de las siguientes finalidades: (i) cumplir las políticas y procedimientos internos de la empresa, (ii) cumplimiento de la legislación aplicable y vigente y requerimientos de autoridad; (iii) administración de personal; (iv) generación de estudios, estadísticas, métricas, programas, reportes y proyectos; (v) evaluar la calidad del servicio; (vi) envío de material publicitario y promocional; (vii) seguimiento de nuestros clientes; (viii) envío de información sobre productos, programas, y sus actualizaciones; (ix) registro de usuarios, clientes y proveedores; (x) recepción, documentación y seguimiento de quejas, que en su caso apliquen; (xi) registro y activación de garantías que en su caso apliquen; (xii) registro de acceso y seguridad; (xiii) Reclutamiento y Selección de personal Externo; (xiv) cumplimiento de obligaciones con clientes y proveedores; (xv) visita de promoción a clientes (xvi) coordinación de alianzas con otros proveedores de servicios; (xvii) documentación y seguimiento de eventos reportables, si es que se presentaran; (xviii) proveer servicios y productos; y (xix) informar sobre cambios o nuevos productos o servicios que estén relacionados con el contratado o adquirido por el cliente (xx)</p>
<p><strong>PROCEDIMIENTO PARA SOLICITUD DE DERECHOS ARCO</strong></p>
<p>El mecanismo que se ha implementado para el ejercicio de los derechos ARCO es a través del envío de una solicitud dirigida al Responsable de Privacidad de Datos de Todo en Tutores SA de CV, a la dirección de correo electrónico contacto-tlalpan@tutordoctor.com.mxo bien, de forma personal en el domicilio mencionado en el presente aviso de Privacidad. En su solicitud por correo electrónico o de forma personal deberá cumplir todos los requisitos que a continuación se enlistan:</p>
<ol>
<li>Proporcionar la siguiente información:<br />
a. Nombre y apellidos;<br />
b. Correo electrónico;<br />
c. Teléfono de contacto<br />
d. Medio por el cual desea se le comunique la respuesta a su solicitud<br />
e. Ciudad y Estado;</li>
<li>Adjuntar o mostrar una copia de los documentos oficiales que acrediten su identidad (credencial de elector, pasaporte) o, en su caso, los que acrediten la representación legal del titular de acuerdo con la legislación en la materia.</li>
<li>Proporcionar la descripción clara y precisa de los datos personales respecto de los que se busca ejercer alguno de sus derechos ARCO, revocación de consentimiento, o negativa de uso de datos para fines secundarios.</li>
<li>Proporcionar cualquier otro elemento, información o documento del que disponga y que facilite la localización de sus datos personales:<br />
a. Relación que usted ha tenido con Todo en Tutores SA de CV: (por ejemplo: soy estudiante de la materia X);<br />
b. Nombre de área o persona de Todo en Tutores SA de CV que lo contactó;<br />
c. Medio por el cual Todo en Tutores SA de CV lo contactó a usted; o<br />
d. Nombre del producto, servicio, evento o programa por el cual se le contactó.</li>
</ol>
<p>El plazo para proporcionarle una respuesta respecto la determinación adoptada con respecto a su solicitud ARCO es de veinte (20) días hábiles contados a partir de la recepción de su solicitud debidamente llenada.<br />
El plazo antes referido podrá ser ampliado una sola vez por un periodo igual, siempre y cuando así lo justifiquen las circunstancias del caso.</p>
<p><strong>¿Cómo puedo revocar mi consentimiento para el uso de sus datos personales?</strong></p>
<p>Usted puede revocar el consentimiento que, en su caso, nos haya otorgado para el tratamiento de sus datos personales. Sin embargo, es importante que tenga en cuenta que no en todos los casos podremos atender su solicitud o concluir el uso de forma inmediata, ya que es posible que por alguna obligación legal requiramos seguir tratando sus datos personales. Asimismo, usted deberá considerar que para ciertos fines, la revocación de su consentimiento implicará que no le podamos seguir prestando el servicio que nos solicitó, o la conclusión de su relación con nosotros.<br />
Para revocar su consentimiento deberá presentar su solicitud a través del “procedimiento para solicitud de derechos ARCO, revocación de consentimiento, o negativa de uso de datos personales para fines secundarios”.</p>
<p><strong>¿Sus datos pueden ser transferidos o ser compartidos con otros?</strong></p>
<p>Sus datos personales pueden ser transferidos, y tratados dentro y fuera de los Estados Unidos Mexicanos, por personas distintas a Todo en Tutores SA de CV. En ese sentido, su información puede ser compartida con otras empresas de Tutor Doctor, filiales, proveedores, autoridades, distribuidores, colaboradores, socios comerciales, o agentes para ayudarnos a brindarle servicios o realizar los tratamientos autorizados por la ley.<br />
Nos comprometemos a no transferir su información personal a terceros distintos a los indicados anteriormente, sin su consentimiento, salvo las excepciones previstas en el artículo 37 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, así como a realizar esta transferencia en los términos que fija esa ley.<br />
Salvo en los casos del artículo 37 de la Ley: Si usted no manifiesta su oposición para que sus datos personales sean transferidos, se entenderá que ha otorgado su consentimiento para ello.<br />
En virtud de que transferiremos algunos datos personales sensibles, requerimos de su consentimiento expreso. Al enviarnos datos personales sensibles a través de los Sitios de Todo en Tutores SA de CV, usted otorga su consentimiento expreso y acepta expresamente que estos datos sean tratados conforme a los términos y condiciones del presente aviso de privacidad.</p>
<h2>Almacenamiento de la información personal</h2>
<p>Utilizamos, procesamos y almacenamos información personal mientras sea necesario para los fines descritos en esta Política de Privacidad, de lo contrario el usuario puede demandar cumplir con el fin de las leyes aplicables y las políticas internas de la empresa. Utilizamos métodos seguros para destruir la información personal cuando ya no se necesita, incluyendo el uso de medidas razonables de seguridad técnica y físicas para evitar el acceso no autorizado o el uso de la información personal después de que se dispone.</p>
<h2>Enlaces a otros sitios</h2>
<p>Para mejorar su experiencia de compra, nuestro sitio web puede incluir enlaces a otros sitios fuera de nuestra familia de marcas. Estos sitios web tienen sus propias políticas de privacidad que puede que desee revisar. No tenemos ninguna responsabilidad sobre estos sitios enlazados, fuera de nuestra familia de marcas.</p>
<h2>Cookies y web beacons</h2>
<p>Las cookies son pequeños ficheros de datos que se almacenan automáticamente en su computadora cuando usted visita nuestros sitios web. Las cookies se utilizan para realizar un seguimiento de las páginas de los sitios web visitados y no se retiene ninguna información de identificación personal, como su nombre, dirección o cualquier otra información financiera. Podemos utilizar cookies para que pueda utilizar algunas funciones del sitio web, recuerde los artículos en su pedido, almacenar sus preferencias, reconocer cuando regrese a nuestro sitio web. La mayoría de los navegadores de Internet aceptan las cookies automáticamente, pero si usted no desea tener las cookies en su sistema, puede establecer las preferencias del navegador para rechazarlas o para que le avise cuando se envíen cookies. Con el fin de desactivarlas, por favor consulte a su navegador &#8220;ayuda&#8221; para obtener instrucciones. Además, si usted tiene un reproductor de Flash instalado en su ordenador, el reproductor de Flash puede ser configurado para rechazar o borrar las cookies de Flash. Si selecciona rechazar las cookies, es posible que no pueda aprovechar en su totalidad las características de nuestro sitio web. Los web beacons son pequeñas cadenas de código que se colocan en una página web o en un mensaje de correo electrónico. A veces se llaman &#8220;GIF transparentes&#8221; (Graphics Interchange Format) o &#8220;pixel tags&#8221;. Los web beacons suelen utilizarse en combinación con las cookies para rastrear la actividad en nuestros sitios web. Cuando usted visita una página web en particular, los web beacons nos notifique de su visita. Dado que los web beacons son utilizados en combinación con las cookies, si deshabilita las cookies de los contadores de visitantes sólo detectará una visita de sitio web anónimo. Cuando se utiliza en un correo electrónico, web beacons nos permiten saber si se ha recibido el correo electrónico.</p>
<h2>Seguridad</h2>
<p>La seguridad de su información es muy importante para nosotros. Tomamos las medidas técnicas y organizativas para proteger sus datos personales contra la destrucción accidental o ilícita, alteración, divulgación o acceso no autorizados, en particular cuando el tratamiento incluya la transmisión de datos a través de una red. Utilizamos últimas tecnologías para proteger la seguridad de su información. Tenga en cuenta que el 100% de seguridad no siempre es posible. Usted juega un papel en la protección de su información también por favor mantenga en secreto sus datos personales y no divulgue ninguno de ellos a terceros, si es que usted no lo desea.</p>
<h2>Privacidad de los niños</h2>
<p>Estamos preocupados por la privacidad de los niños pequeños y no recogemos ninguna información personal de un niño. No vendemos productos para ser comprados por niños.</p>
<h2>Actualizaciones políticas de privacidad</h2>
<p>Podemos actualizar nuestra política de privacidad de vez en cuando. Cada vez que hacemos un cambio, publicaremos la política actualizada en el sitio web Tutorestlalpan.com.mx y le animamos a que consulte nuestra política periódicamente. Si hacemos un cambio en nuestra política de privacidad que pueda reducir sus derechos de privacidad o requerirá su consentimiento, o bien seguirá cumpliendo nuestra política previa para la información que hemos recogido cuando estaba en vigor, o le pediremos su consentimiento para cambiar. Si usted tiene alguna pregunta o inquietud con respecto a nuestra política de privacidad, por favor póngase en contacto con nosotros a través de la sección contacto.</p>


    </div>
</section>
